### ISSUE TITLE
【Question】TCGAquery_recount2 function

### ISSUE THREAD

**Issue by WHOISSIILVIA** [ELELAB/TCGAbiolinks_examples#1]
These days, I tried to use the TCGAquery_recount2 function to download tumor and normal uterine samples, but failed. The codes are as follow.I wonder if there is the problem in the platform.
Looking forward to your reply!

#######################################################################
ucs.recount.gtex <- TCGAquery_recount2(project = "GTEX", tissue="uterus")
downloading Range Summarized Experiment for: uterus
Error in load(url(con)) : error reading from connection

**Comment by elenapapaleo** [comment]
We didn't see this sorry. If any relevant, when you get that kind of error it might be a server problem, or a firewall blocking the access. It works on my side with TCGAbiolinks version 2.20 on my Mac for example.
